package com.forum.units;

public class Upvote extends AbstractEntity {
	//question for which user has upvoted
	private Question question;
	//reply for which user has upvoted
	private Reply reply;
	//user who has upvoted for either of question xor answer
	private User user;
	//id for the last upvote on discussion forum
	private static Long lastEntry = 0L;
	


	
	public Question getQuestion() {
		return question;
	}
	
	public void setQuestion(Question question) {
		this.question = question;
	}
	
	public Reply getReply() {
		return reply;
	}
	
	public void setReply(Reply reply) {
		this.reply = reply;
	}
	
	public User getUser() {
		return user;
	}
	
	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public void autoGeneratedId() {
		lastEntry = lastEntry + 1L;
		super.setId(lastEntry);

		// please write your code below and follow this instruction:
		// 1. Call the parent class' setId method and pass in lastEntry as the method variable;
		//
		// Note: You can read the setId method in the AbstractEntity class to understand how the setId method works
	}
}
